services:
  postgres:
    image: postgres
    container_name: trpc-postgres
    # volumes:
    #   - "/etc/postgresql"
    #   - "/var/log/postgresql"
    #   - "/var/lib/postgresql"
    #   - ./postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
